import Forecast from "../interfaces/forecast";

const alert = {
  headline: "string",
  msgtype: "string",
  severity: "string",
  urgency: "string",
  areas: "string",
  category: "string",
  certainty: "string",
  event: "string",
  note: "string",
  effective: "string",
  expires: "string",
  desc: "string",
  instruction: "string",
};

const forecastHour = {
  time_epoch: 1,
  time: "string",
  temp_c: 1,
  temp_f: 1,
  is_day: 1,
  condition: {
    text: "string",
    icon: "string",
    code: 1,
  },
  wind_mph: 1,
  wind_kph: 1,
  wind_degree: 1,
  wind_dir: "string",
  pressure_mb: 1,
  pressure_in: 1,
  precip_mm: 1,
  precip_in: 1,
  humidity: 1,
  cloud: 1,
  feelslike_c: 1,
  feelslike_f: 1,
  windchill_c: 1,
  windchill_f: 1,
  heatindex_c: 1,
  heatindex_f: 1,
  dewpoint_c: 1,
  dewpoint_f: 1,
  will_it_rain: 1,
  chance_of_rain: 1,
  will_it_snow: 1,
  chance_of_snow: 1,
  vis_km: 1,
  vis_miles: 1,
  gust_mph: 1,
  gust_kph: 1,
  uv: 1,
};

const forecastDay = {
  date: "string",
  date_epoch: 1,
  day: {
    maxtemp_c: 1,
    maxtemp_f: 1,
    mintemp_c: 1,
    mintemp_f: 1,
    avgtemp_c: 1,
    avgtemp_f: 1,
    maxwind_mph: 1,
    maxwind_kph: 1,
    totalprecip_mm: 1,
    totalprecip_in: 1,
    avgvis_km: 1,
    avgvis_miles: 1,
    avghumidity: 1,
    daily_will_it_rain: 1,
    daily_chance_of_rain: 1,
    daily_will_it_snow: 1,
    daily_chance_of_snow: 1,
    condition: {
      text: "string",
      icon: "string",
      code: 1,
    },
    uv: 1,
  },
  astro: {
    sunrise: "string",
    sunset: "string",
    moonrise: "string",
    moonset: "string",
    moon_phase: "string",
    moon_illumination: "string",
  },
  hour: [forecastHour],
};

const forecast: Forecast = {
  location: {
    name: "string",
    region: "string",
    country: "string",
    lat: 1,
    lon: 1,
    tz_id: "string",
    localtime_epoch: 1,
    localtime: "string",
  },
  current: {
    last_updated_epoch: 1,
    last_updated: "string",
    temp_c: 1,
    temp_f: 1,
    is_day: 1,
    condition: {
      text: "string",
      icon: "string",
      code: 1,
    },
    wind_mph: 1,
    wind_kph: 1,
    wind_degree: 1,
    wind_dir: "string",
    pressure_mb: 1,
    pressure_in: 1,
    precip_mm: 1,
    precip_in: 1,
    humidity: 1,
    cloud: 1,
    feelslike_c: 1,
    feelslike_f: 1,
    vis_km: 1,
    vis_miles: 1,
    uv: 1,
    gust_mph: 1,
    gust_kph: 1,
  },
  forecast: {
    forecastday: [forecastDay],
  },
  alerts: {
    alert: [alert],
  },
};

export default forecastDay;
